### ISSUE TITLE
Remove Electrum ping log

### ISSUE THREAD

**Issue by louneskmt** [bitcoinerlab/explorer#2]
Hey!

Would you be okay to remove this log, or hide it behind a configuration option? One per second can flood the logs pretty quickly. I'd have gladly proposed to open a PR for this if it wasn't just a line deletion haha

https://github.com/bitcoinerlab/explorer/blob/cc52126568ed9ec61d84a5ef6425f6855cb0572f/src/electrum.ts#L182

**Comment by landabaso** [comment]
Thanks for the heads-up! Do you need an immediate npm release for this fix, or can it wait for the next update?

BTW, it's 1 per min (not sec)

**Comment by louneskmt** [comment]
Yep sorry, I meant minute. 

I patched the dependency for now so there is no rush for a npm release, all good. Thanks!

**Comment by vafanassieff** [comment]
> Thanks for the heads-up! Do you need an immediate npm release for this fix, or can it wait for the next update?
> 
> BTW, it's 1 per min (not sec)

It can wait a little bit, maybe you can make log optional and behind a flag ?

**Comment by landabaso** [comment]
Hello @louneskmt, @vafanassieff,

If you are currently using `@bitcoinerlab/explorer` in conjunction with `@bitcoinerlab/discovery`, I strongly recommend upgrading both packages. The latest version of `@bitcoinerlab/discovery` includes significant performance improvements, specifically through enhanced parallelization in fetching outputs. This update should provide a notable boost in efficiency for your implementations. Let me know if you find any issue.
